"""Core module for generating C++ command catalog include files."""

import logging
from operator import attrgetter
from pathlib import Path
from typing import Final

from .types import ContextMenuItem

logger = logging.getLogger(__name__)

# Target relative output directory and filename for generated C++ includes
OUTPUT_DIRECTORY: Final = Path("src/generated")
OUTPUT_FILE_NAME: Final = "GeneratedCommands.inc"


def generate_command_catalog(
    commands: list[ContextMenuItem],
    output_dir: Path,
):
    """Generates a C++ include file containing the command metadata catalog.

    Sorts the provided context menu items by ID and formats each item into a C++
    literal representation, writing the compiled result to `GeneratedCommands.inc`.

    Args:
        commands (list[ContextMenuItem]): List of extracted context menu items.
        output_dir (Path): Base output directory where the generated file structure
            will be created.
    """
    # Ensure deterministic output ordering by sorting commands by ID
    commands.sort(key=attrgetter("id"))

    # Prepare destination directory path
    out_dir = output_dir / OUTPUT_DIRECTORY
    out_dir.mkdir(parents=True, exist_ok=True)

    catalog_data_file = out_dir / OUTPUT_FILE_NAME

    # Write generated C++ initialization entries with UTF-8 BOM encoding
    with catalog_data_file.open("w", encoding="utf-8-sig") as f:
        f.write(f"""\
// <auto-generated>
// This file is automatically generated by {__package__}.
// Do not hand-edit this file directly.
// </auto-generated>

""")
        f.write(",\n".join(cmd.to_cpp_literal() for cmd in commands))

    logger.info("Successfully generated command catalog: %s", catalog_data_file.resolve())
